name: Docker

on:
  push:
    tags:
      - "**"

    branches:
      - main

jobs:
  test:
    uses: ./.github/workflows/template-test.yml

  docker:
    name: Docker build
    needs:
      - test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      discussions: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: docker-meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/multani/pubsub-emulator
          tags: |
            type=ref,event=tag
            type=raw,value=latest
            type=sha

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ steps.docker-meta.outputs.tags }}
          labels: ${{ steps.docker-meta.outputs.labels }}

      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        with:
          name: ${{ github.ref_name }}
          discussion_category_name: announcements
          generate_release_notes: true
          body: |-
            Get the Docker image at [ghcr.io/multani/pubsub-emulator:${{ github.ref_name }}](https://github.com/multani/pubsub-emulator/pkgs/container/pubsub-emulator/)

            ```
            $ docker pull ghcr.io/multani/pubsub-emulator:${{ github.ref_name }}
            ```
